version: 0.2

env:
  secrets-manager:
    NPM_TOKEN: "npm-token:npm-token"

phases:
  install:
    commands:
      - yum install jq -y
      - jq --version
      - echo ${NPM_TOKEN}.npm-token
      - echo `$NPM_TOKEN | jq -r '.npm-token'`
      - echo "//point-cloud-visualiser/:_authToken=$NPM_TOKEN"
      - echo "//point-cloud-visualiser/:_authToken=${NPM_TOKEN}"
      - echo "//point-cloud-visualiser/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - npm set //point-cloud-visualiser/:_authToken $NPM_TOKEN
      - npm install
  build:
    commands:
      - npm run build
      - npm publish