version: 0.2

env:
  secrets-manager:
    NPM_TOKEN: "npm-token"

phases:
  install:
    commands:
      - echo "//point-cloud-visualiser:8080/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - npm install
  build:
    commands:
      - npm run build
      - npm publish