version: 0.2

env:
  secrets-manager:
    NPM_TOKEN: "npm-token:npm-token"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm config set registry 'https://www.npmjs.com/package/point-cloud-visualiser'
      - npm config set '//registry.npmjs.org/:always-auth' 'true'
      - npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
      - npm publish