version: 0.2

env:
  secrets-manager:
    NPM_TOKEN: "npm-token"

phases:
  install:
    commands:
      - node --version
      - npm install
  build:
    commands:
      - npm run build
      - npm publish