version: 0.2

env:
  secrets-manager:
    NPM_TOKEN: "npm-token:npm-token"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - echo "//registry.npmjs.org/:always-auth=true" >> ~/.npmrc
      - npm publish