version: 0.2

env:
  secrets-manager:
    NPM_TOKEN: "npm-token:npm-token"

phases:
  install:
    commands:
      - echo "//https://registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - npm set //https://registry.npmjs.org/:_authToken $NPM_TOKEN
      - npm install
  build:
    commands:
      - npm run build
      - npm publish