version: 0.2h

env:
  secrets-manager:
    NPM_TOKEN: "npm-token"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm publish